remoteBuild:
  enabled: true
  requestMemory: 4096
  runnerCommand: >
    export SHELL=/bin/bash;
    unset PYTHONPATH;
    source /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/{LSST_VERSION}/loadLSST.bash;
    pwd;ls -al;
    setup lsst_distrib;
    echo "setup tokens";
    if [[ ! -z "${PANDA_AUTH_DIR}" ]] && [[ ! -z "${PANDA_AUTH_ORIGIN}" ]];
    then export PANDA_AUTH_ID_TOKEN=$(cat $PANDA_AUTH_DIR);
    export PANDA_AUTH_VO=$PANDA_AUTH_ORIGIN;
    export IDDS_OIDC_TOKEN=$(cat $PANDA_AUTH_DIR);
    export IDDS_VO=$PANDA_AUTH_ORIGIN;
    export PANDA_AUTH=oidc;
    else unset PANDA_AUTH;
    export IDDS_AUTH_TYPE=x509_proxy; fi;
    export PANDA_CONFIG_ROOT=$(pwd);
    export PANDA_VERIFY_HOST=off;
    export PANDA_SYS=$CONDA_PREFIX;
    export PANDA_URL_SSL=${PANDA_SERVER_URL}/server/panda;
    export PANDACACHE_URL=$PANDA_SERVER_URL;
    export PANDA_URL=$PANDA_URL_SSL;
    {custom_lsst_setup}
    python3 ${CTRL_BPS_PANDA_DIR}/python/lsst/ctrl/bps/panda/edgenode/build_cmd_line_decoder.py _download_cmd_line_ _build_cmd_line_
